### ISSUE TITLE
doesn't work with schemaextended content

### ISSUE THREAD

**Issue by thet** [zopyx/zopyx.plone.migration#6]
archetypes.schemaextender extended schemas are not exported (likely also not imported). I encountered this problem witch collective.contentleadimage. ``obj.Schema().fields()`` ( https://github.com/bluedynamics/zopyx.plone.migration/blob/a2f7d9f81d2e2631ce5c2bdfd783e6c43bed49fe/zopyx/plone/migration/exporter.py#L409 ) does only return the directly owned schema.

* Wether, it's that the request is missing the browserlayer, which is necessary for the contentleadimage's ``IBrowserLayerAwareExtender`` (it's missing it - ``IBrowserLayerAwareExtender.providedBy(options.plone.REQUEST) == False``)

* Or Zope did not load the necessary ZCML properly?

However, there is a workaround. In the contenttype's own schema, temporarily copy the necessary fields for exporting and importing, and remove it after importing.

**Comment by zopyx** [comment]
i don't plan further changes at the moment since we have our own copy of this script with many customizations for every project.

**Comment by thet** [comment]
no prob! tnx for merging the other pull request anyways.
